package de.daveos.enderiofabriclight.block;

import com.mojang.serialization.MapCodec;
import de.daveos.enderiofabriclight.blockentity.ConduitBlockEntity;
import de.daveos.enderiofabriclight.inventory.InventorySource;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.util.RandomSource;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelReader;
import net.minecraft.world.level.ScheduledTickAccess;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.EntityBlock;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.EnumProperty;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

import java.util.EnumMap;
import java.util.Map;
import java.util.function.Function;

/**
 * The conduit (pipe) block: a thin glass tube with a glowing core. Each side is {@link ConduitConnection#NONE},
 * {@link ConduitConnection#PIPE} (another conduit) or {@link ConduitConnection#PLUG} (storage or a terminal's
 * back), recomputed on placement and whenever a neighbour changes.
 *
 * <p>Models are generated by {@code gen_conduit.py}; hitbox dimensions here must match it.
 */
public class ConduitBlock extends Block implements EntityBlock {
    public static final MapCodec<ConduitBlock> CODEC = simpleCodec(ConduitBlock::new);

    public static final EnumProperty<ConduitConnection> NORTH = EnumProperty.create("north", ConduitConnection.class);
    public static final EnumProperty<ConduitConnection> EAST = EnumProperty.create("east", ConduitConnection.class);
    public static final EnumProperty<ConduitConnection> SOUTH = EnumProperty.create("south", ConduitConnection.class);
    public static final EnumProperty<ConduitConnection> WEST = EnumProperty.create("west", ConduitConnection.class);
    public static final EnumProperty<ConduitConnection> UP = EnumProperty.create("up", ConduitConnection.class);
    public static final EnumProperty<ConduitConnection> DOWN = EnumProperty.create("down", ConduitConnection.class);

    public static final Map<Direction, EnumProperty<ConduitConnection>> PROPERTY_BY_DIRECTION = new EnumMap<>(Map.of(
        Direction.NORTH, NORTH, Direction.EAST, EAST, Direction.SOUTH, SOUTH,
        Direction.WEST, WEST, Direction.UP, UP, Direction.DOWN, DOWN));

    private static final VoxelShape CORE = Block.box(5, 5, 5, 11, 11, 11);
    private static final Map<Direction, VoxelShape> ARM = new EnumMap<>(Direction.class);
    private static final Map<Direction, VoxelShape> PLATE = new EnumMap<>(Direction.class);
    static {
        for (Direction dir : Direction.values()) {
            ARM.put(dir, towards(dir, 6, 10, 0, 6));
            PLATE.put(dir, towards(dir, 4, 12, 0, 1));
        }
    }

    private final Function<BlockState, VoxelShape> shapes;

    public ConduitBlock(Properties properties) {
        super(properties);
        BlockState state = this.stateDefinition.any();
        for (EnumProperty<ConduitConnection> p : PROPERTY_BY_DIRECTION.values()) {
            state = state.setValue(p, ConduitConnection.NONE);
        }
        this.registerDefaultState(state);
        this.shapes = getShapeForEachState(ConduitBlock::computeShape);
    }

    @Override
    protected MapCodec<? extends Block> codec() {
        return CODEC;
    }

    @Override
    protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
        builder.add(NORTH, EAST, SOUTH, WEST, UP, DOWN);
    }

    // --- Shape --------------------------------------------------------------

    /**
     * Box spanning {@code c0..c1} on the two cross axes and {@code d0..d1} measured inward from the
     * block face on side {@code dir}.
     */
    private static VoxelShape towards(Direction dir, double c0, double c1, double d0, double d1) {
        double lo = dir.getAxisDirection() == Direction.AxisDirection.NEGATIVE ? d0 : 16 - d1;
        double hi = dir.getAxisDirection() == Direction.AxisDirection.NEGATIVE ? d1 : 16 - d0;
        return switch (dir.getAxis()) {
            case X -> Block.box(lo, c0, c0, hi, c1, c1);
            case Y -> Block.box(c0, lo, c0, c1, hi, c1);
            case Z -> Block.box(c0, c0, lo, c1, c1, hi);
        };
    }

    private static VoxelShape computeShape(BlockState state) {
        VoxelShape shape = CORE;
        for (Map.Entry<Direction, EnumProperty<ConduitConnection>> e : PROPERTY_BY_DIRECTION.entrySet()) {
            ConduitConnection c = state.getValue(e.getValue());
            if (c.isConnected()) shape = Shapes.or(shape, ARM.get(e.getKey()));
            if (c == ConduitConnection.PLUG) shape = Shapes.or(shape, PLATE.get(e.getKey()));
        }
        return shape;
    }

    @Override
    protected VoxelShape getShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
        return shapes.apply(state);
    }

    // --- Connections --------------------------------------------------------

    @Override
    public BlockState getStateForPlacement(BlockPlaceContext context) {
        Level level = context.getLevel();
        BlockPos pos = context.getClickedPos();
        BlockState state = defaultBlockState();
        for (Direction dir : Direction.values()) {
            BlockPos neighbor = pos.relative(dir);
            state = state.setValue(PROPERTY_BY_DIRECTION.get(dir),
                connectionTo(level, neighbor, level.getBlockState(neighbor), dir));
        }
        return state;
    }

    @Override
    protected BlockState updateShape(BlockState state, LevelReader level, ScheduledTickAccess tickAccess,
                                     BlockPos pos, Direction direction, BlockPos neighborPos,
                                     BlockState neighborState, RandomSource random) {
        return state.setValue(PROPERTY_BY_DIRECTION.get(direction),
            connectionTo(level, neighborPos, neighborState, direction));
    }

    /**
     * {@code dir} points from this conduit to the neighbour. A terminal's back faces us exactly when
     * its screen faces the same way.
     */
    private static ConduitConnection connectionTo(LevelReader level, BlockPos neighborPos, BlockState neighborState, Direction dir) {
        if (neighborState.is(ModBlocks.CONDUIT)) return ConduitConnection.PIPE;
        if (neighborState.is(ModBlocks.TERMINAL)) {
            return neighborState.getValue(TerminalBlock.FACING) == dir ? ConduitConnection.PLUG : ConduitConnection.NONE;
        }
        BlockEntity be = level.getBlockEntity(neighborPos);
        return be != null && InventorySource.isAllowedInventory(be) ? ConduitConnection.PLUG : ConduitConnection.NONE;
    }

    @Override
    public BlockEntity newBlockEntity(BlockPos pos, BlockState state) {
        return new ConduitBlockEntity(pos, state);
    }
}
