"""One-off generator for simple procedural 16x16 block textures (RGBA PNG).
Pure stdlib (zlib) — no PIL. Run once; the PNGs are the real assets, this script
is just tooling and can be deleted afterwards.
"""
import zlib, struct, os

W = H = 16
OUT = os.path.join("src", "main", "resources", "assets", "enderio-fabric-light", "textures", "block")


def png(path, px):
    raw = bytearray()
    for y in range(H):
        raw.append(0)  # filter: none
        for x in range(W):
            r, g, b, a = px[y][x]
            raw += bytes((r, g, b, a))
    comp = zlib.compress(bytes(raw), 9)

    def chunk(typ, data):
        return struct.pack(">I", len(data)) + typ + data + struct.pack(">I", zlib.crc32(typ + data) & 0xffffffff)

    blob = (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", W, H, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", comp)
            + chunk(b"IEND", b""))
    with open(path, "wb") as f:
        f.write(blob)
    print("wrote", path)


def grid(fill):
    return [[tuple(fill) for _ in range(W)] for _ in range(H)]


def edge(px, color):
    for i in range(W):
        px[0][i] = color
        px[H - 1][i] = color
        px[i][0] = color
        px[i][W - 1] = color


def rect(px, x0, y0, x1, y1, color):
    for y in range(y0, y1):
        for x in range(x0, x1):
            px[y][x] = color


# Conduit textures and models are generated by gen_conduit.py.


# --- Terminal front: a glowing screen in a metal bezel ---------------------
def terminal_front():
    bezel = (58, 63, 72, 255)
    bezel_dk = (32, 35, 41, 255)
    bezel_lt = (84, 90, 100, 255)
    screen_bg = (16, 38, 44, 255)
    screen_lit = (44, 184, 192, 255)
    screen_dim = (28, 96, 104, 255)
    px = grid(bezel)
    edge(px, bezel_dk)
    # bezel highlight
    for i in range(1, W - 1):
        px[1][i] = bezel_lt
        px[i][1] = bezel_lt
    # screen area 3..13
    rect(px, 3, 3, 13, 13, screen_bg)
    # a few "display" rows to suggest a list of items
    for y in (4, 6, 8, 10):
        rect(px, 4, y, 12, y + 1, screen_dim)
    # a couple of brighter cells
    rect(px, 4, 4, 6, 5, screen_lit)
    rect(px, 8, 6, 11, 7, screen_lit)
    rect(px, 4, 8, 7, 9, screen_lit)
    png(os.path.join(OUT, "terminal_front.png"), px)


# --- Terminal side: plain metal casing with two grooves --------------------
def terminal_side():
    base = (74, 80, 90, 255)
    dark = (40, 44, 51, 255)
    light = (100, 107, 118, 255)
    groove = (52, 57, 65, 255)
    px = grid(base)
    edge(px, dark)
    for i in range(1, W - 1):
        px[1][i] = light
        px[i][1] = light
    rect(px, 2, 5, 14, 6, groove)
    rect(px, 2, 10, 14, 11, groove)
    png(os.path.join(OUT, "terminal_side.png"), px)


# --- Wrench item: diagonal open-end wrench, graphite with a teal grip -------
def wrench():
    import math
    outline = (24, 27, 32, 255)
    metal_hi = (196, 204, 214, 255)
    metal = (150, 158, 170, 255)
    metal_lo = (104, 111, 122, 255)
    grip = (44, 184, 192, 255)
    grip_lo = (26, 118, 124, 255)

    def seg_dist(px_, py_, ax, ay, bx, by):
        dx, dy = bx - ax, by - ay
        t = max(0.0, min(1.0, ((px_ - ax) * dx + (py_ - ay) * dy) / (dx * dx + dy * dy)))
        return math.hypot(px_ - (ax + t * dx), py_ - (ay + t * dy))

    fill = {}
    for y in range(H):
        for x in range(W):
            cx, cy = x + 0.5, y + 0.5
            # Across the handle: negative = upper-left edge (lit), positive = lower-right (shaded).
            across = ((cx - 2.5) + (cy - 13.5)) / math.sqrt(2)
            if seg_dist(cx, cy, 2.5, 13.5, 9.5, 6.5) < 1.25:
                is_grip = cx < 6.5
                if is_grip:
                    fill[(x, y)] = grip if across < 0.4 else grip_lo
                else:
                    fill[(x, y)] = metal_hi if across < -0.3 else metal if across < 0.5 else metal_lo
            # Open-end head: a disc around (11.5, 4.5) with a straight slot cut in toward the top-right.
            dxj, dyj = cx - 11.5, cy - 4.5
            along = (dxj - dyj) / math.sqrt(2)
            perp = (dxj + dyj) / math.sqrt(2)
            if math.hypot(dxj, dyj) < 3.4 and not (abs(perp) < 1.0 and along > -0.8):
                fill[(x, y)] = metal_hi if perp < 0 else metal

    px = grid((0, 0, 0, 0))
    for (x, y), c in fill.items():
        px[y][x] = c
    for y in range(H):
        for x in range(W):
            if (x, y) in fill:
                continue
            if any((x + ox, y + oy) in fill for ox, oy in ((1, 0), (-1, 0), (0, 1), (0, -1))):
                px[y][x] = outline
    out = os.path.join(os.path.dirname(OUT), "item")
    os.makedirs(out, exist_ok=True)
    png(os.path.join(out, "wrench.png"), px)


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    terminal_front()
    terminal_side()
    wrench()
    print("done")
